#!/bin/bash

## Installatio
APP_NAME=touchevent
WWW=/var/www/$APP_NAME
API=/var/node/$APP_NAME
USER=node
ADMIN_USERNAME=admin
ADMIN_PASSWORD=touchevent
SERVER_HOST="127.0.0.1:8080"

setup_build_tools(){
	trap 'print_error $LINENO' ERR
	print_begin "setting up build tools"
	sudo apt-get update
	sudo apt-get install -y build-essential
	sudo apt-get install -y libkrb5-dev
	sudo apt-get install -y git
	sudo apt-get install -y apache2-utils
	sudo apt-get install python
	sudo echo && echo "$(tput setaf 2)OK$(tput sgr0)"
}

setup_node_js(){
	trap 'print_error $LINENO' ERR
	print_begin "setting up node.js"
	curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
	sudo apt-get install -y nodejs
	sudo echo && echo "$(tput setaf 2)OK$(tput sgr0)"
}

setup_mongo_db(){
	trap 'print_error $LINENO' ERR
	print_begin "setting up mongodb 3.2"$(tput sgr0)""
	sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv EA312927
    echo "deb http://repo.mongodb.org/apt/ubuntu "$(lsb_release -sc)"/mongodb-org/3.2 multiverse" \
    	| sudo tee /etc/apt/sources.list.d/mongodb.list
    sudo apt-get update
    sudo apt-get install -y mongodb-org
	sudo cp ./disable-transparent-hugepages /etc/init.d
	sudo chmod 755 /etc/init.d/disable-transparent-hugepages
	sudo update-rc.d disable-transparent-hugepages defaults
	sudo service disable-transparent-hugepages start
	MONGO_PROCESS=$(ps -eF | grep mongod | head -1 | awk '{print $1}')
	if [ ! -n "$MONGO_PROCESS" ]; then
		sudo service mongod start
	fi
	sudo echo && echo "$(tput setaf 2)OK$(tput sgr0)"
}

setup_nginx(){
	trap 'print_error $LINENO' ERR
	print_begin "setting up nginx web server 1.4"
	sudo apt-get install -y nginx
	sed -i -e "s/<APP_NAME>/${APP_NAME}/" ./default
	sudo cp ./default /etc/nginx/sites-enabled/default
	sudo service nginx reload
	sudo echo && echo "$(tput setaf 2)OK$(tput sgr0)"
}

install_files(){
	trap 'print_error $LINENO' ERR
	print_begin "installing server and client files"
	sed -i -e "s/<SERVER_HOST>/${SERVER_HOST}/" ./client/app/config/cfg.json
	SECRET=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)
	sed -i -e "s/<APP_NAME>/${APP_NAME}/" -e "s/<SECRET>/${SECRET}/" ./server/app/cfg.js
	if [ ! -d "$WWW" ]; then
		sudo mkdir -p "$WWW"
	fi
	sudo cp -r ./client/app/* "$WWW"
	sudo chown -R "$USER" "$WWW"
	if [ ! -d "$API" ]; then
		sudo mkdir -p "$API"
	fi
	sudo cp -r ./server/* "$API"
	sudo chown -R "$USER" "$API"
	sudo echo && echo "$(tput setaf 2)OK$(tput sgr0)"
}

setup_server() {
	trap 'print_error $LINENO' ERR
	print_begin "setting up server dependencies and startup"
	sudo npm install -g pm2
	sudo pm2 startup ubuntu -u $USER
	sudo cp ./pm2-init.sh /etc/init.d/
	sudo chmod 755 /etc/init.d/pm2-init.sh
	sudo chown -R "$USER" "$API"
	sudo chown -R "$USER" "$WWW"
	cd "$API"
	if [ -d node_modules ]; then
		sudo rm -rf node_modules
	fi
	sudo su $USER -c "npm install --no-bin-links"
	HASH=$(echo "$ADMIN_PASSWORD" \
		| htpasswd -n -i -B -C 10 username  \
		| tr -d '\n' \
		| awk -F: '{ print $2 }')
    DB_COMMAND='db.users.insert({username:"'
	DB_COMMAND+=$ADMIN_USERNAME
	DB_COMMAND+='",password:"'
	DB_COMMAND+=$HASH
	DB_COMMAND+='", registered_at: new Date()})'
	export LC_ALL=C
	echo && echo "Mongodb command: $DB_COMMAND"
	mongo $APP_NAME --eval "$DB_COMMAND"
	sudo echo && echo "$(tput setaf 2)OK$(tput sgr0)"
}

start_server(){
	trap 'print_error $LINENO' ERR
	print_begin "starting server"
	sudo su -l $USER -c "pm2 start $API/app/server.js"
	sudo su -l $USER -c "pm2 save"
	print_success
}

restart_server(){
	trap 'print_error $LINENO' ERR
	print_begin "restarting server"
	sudo service pm2-init.sh restart
	print_success
}



create_user() {
	print_begin "restarting server"
	id $USER
	if [ $? = 1 ]; then
		sudo adduser --no-create-home --disabled-password --gecos "api server user" $USER
	fi
	print_success
}

deploy() {
	git add . --all
	git commit -m "$1"
	git push origin dev
}

main() {
	case "$1" in
	    install)
			create_user
			set -e
			setup_build_tools
			setup_node_js
			setup_mongo_db
			setup_nginx
			install_files 
			setup_server
			start_server
			exit 0
	    ;;
	    reload)
			set -e
			install_files
			restart_server
			exit 0
		;;
	    deploy)
			deploy "$2"
		;;
	    *)
	        echo "Usage: {install|deploy|reload}"
	        exit 1
	    ;;
	esac

}

print_begin(){
	echo && echo "$(tput setaf 3)$1$(tput sgr0)"
}

print_success(){
    echo && echo "$(tput setaf 2)OK$(tput sgr0)"
}

print_error() {
    echo "$(tput setaf 1)Error on line $1$(tput sgr0)"
}

main "$1" "$2"


